### ISSUE TITLE
Show wrong network error message when trying to connect with unsupported networks

### ISSUE THREAD

**Issue by penandlim** [saddle-finance/saddle-frontend#700]

**Comment by zimh** [comment]
was gonna create a new ticket but maybe the fix for this can also include fix for weird UI? Or LMK if better to create a separate ticket @sandrasong 

Issue (2): 
- When user is connected to an unsupported network, the UI shows "Ethereum" with green dot
![image](https://user-images.githubusercontent.com/19593719/145447594-8307eb21-c6df-4692-a7fc-a4dedb0c8bc9.png)
- When user is connected to an unsupported network and user attempts to switch to a network using the UI, this error shows:
![image](https://user-images.githubusercontent.com/19593719/145447682-5e0788da-64db-4653-a5bc-5e5a143e8c20.png)

Steps to repro:
- Set metamask to Avalanche (or another unsupported network)
- Observe that UI shows Ethereum with green dot
- Click on Ethereum > Network > Arbitrum
- Observe that nothing happens on the UI (and an error msg is sent in console)

Ideal solution: 
- when user is connected to an unsupported network, the UI should show a red dot instead of green
- when user is connected to an unsupported network and attempts to switch to a supported network, it should either successfully switch networks, or display a message to the user that they need to change network using their wallet first

**Comment by sandrasong** [comment]
Design task addd to this ticket: 
- [ ] Create the wrong network notification
